# Copyright (c) 2018 Intel Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Add go language gophers repo key
  # due to a proxy issue in the ansible apt_key module on Ubuntu 17.10,
  # it doesn't work to add key via `id` and `keyserver` parametes. Similar
  # issue is described here: https://github.com/debops/ansible-elastic_co/issues/2
  #  apt_key:
  #    keyserver: "{{ golang_repo_key_server }}"
  #    id: "{{ golang_repo_key_id }}"
  # As a workaround, we can use `apt-key` tool directly with proxy specified.
  command: >
           apt-key adv --keyserver {{ golang_repo_key_server }} --recv-keys
           --keyserver-options http-proxy={{ proxy_env.http_proxy }}
           {{ golang_repo_key_id }}

- name: Add apt golang repository
  apt_repository:
    repo: "{{ golang_repo_url }}"
    filename: golang-1.10-go

- name: Install golang-1.10-go
  apt:
    name: golang-1.10-go

- name: Setup Go environment variable
  set_fact:
    go_env:
      PATH: "{{ golang_bin_dir }}:{{ ansible_env.PATH }}"
