# Copyright (c) 2018 Intel Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# Arguments needed: map_min_addr_file, yardstick_dir

- name: Define variables
  set_fact:
    map_min_addr_file: "/etc/sysctl.d/mmap_min_addr.conf"

- name: Remove the kernel minimum virtual address restriction that a process is allowed to mmap
  copy:
    dest: "{{ map_min_addr_file }}"
    content: "vm.mmap_min_addr = 0\n"

- name: Config git SSL
  git_config:
    name: http.sslVerify
    scope: global
    value: False

# There is a bug with the easy install ansible module in suse linux.
# Until this is fixed the shell command mus6t be used
- name: Install pip
  shell: easy_install -U pip
#    easy_install:
#    name: pip
#    state: latest


# NOTE: add virtual environment.
- name: Install Yardstick requirements
  pip:
    requirements: "{{ yardstick_dir }}/requirements.txt"

# NOTE: add virtual environment.
- name: Install Yardstick code
  pip:
    name: "{{ yardstick_dir }}/."
    extra_args: -e
