# Copyright (c) 2018 Intel Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Define variables
  set_fact:
    trex_url: "http://artifacts.opnfv.org/yardstick/third-party/trex_client.tar.gz"
    nsb_dir: "/opt/nsb_bin/"

- name: Define TRex file name
  set_fact:
    trex_file_name: "{{ trex_url|basename }}"

- name: Fetch TRex client
  get_url:
    url: "{{ trex_url }}"
    dest: "{{ nsb_dir }}"
    validate_certs: False

- name: Unarchive TRex client
  unarchive:
    src: "{{ nsb_dir }}/{{ trex_file_name }}"
    dest: "{{ nsb_dir }}"
    copy: no

- name: Cleanup file to save space
  file:
      path: "{{ nsb_dir }}/{{ trex_file_name }}"
      state: absent
