---
pkg_mgr_retries: 3
epel_rpm_el7: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

install_dependencies:
  Debian:
    - bc
    - fio
    - git
    - gcc
    - iperf3
    - ethtool
    - iproute2
    - linux-tools-common
    - linux-tools-generic
    - make
    - patch
    - perl
    - rt-tests
    - stress
    - sysstat
    - unzip
    - netperf
    - bonnie++
    - lmbench
    # for Trex
    - libpython2.7-dev
    # for IxLoad
    - libxft-dev
    - libxss-dev
    - expect
  RedHat:
    - bc
    - fio
    - git
    - gcc
    - iperf3
    - ethtool
    - iproute
    - perf
    - kernel-tools
    - lmbench
    - make
    - netperf
    - patch
    - perl
    - rt-tests
    - stress
    - sysstat
    - unzip
    - python-devel
