---
##############################################################################
# Copyright (c) 2017 Huawei Technologies Co.,Ltd and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: archive_spec_cpu2006_result
  archive:
    path: /usr/cpu2006/result
    dest: /usr/cpu2006/spec_cpu2006_result.zip
  become: true
