---
##############################################################################
# Copyright (c) 2017 Huawei Technologies Co.,Ltd and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: compute
  roles:
      - vcpu_pin_set_reset
      - restart_nova_compute

- hosts: controller
  roles:
      - scheduler_default_filters_reset
      - restart_nova_scheduler

- hosts: localhost
  roles:
      - numa_pin_local_teardown
